repos:
  - repo: local
    hooks:
      - id: check-git-signing
        name: Check Git commit signing
        entry: bash hooks/check-signing.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [commit]

