name: Lint Shell Scripts

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck with custom options
        run: |
          find . -type f -name "*.sh" | while read -r file; do
            echo "Linting $file"
            shellcheck --external-sources --shell=bash --source-path=SCRIPTDIR --format=gcc "$file"
          done


